### PR TITLE
Intro to non parametric tests -  Full draft

### PR DESCRIPTION
**Pull request by Aakriti-G**
Dear Hannes
I am sharing the first full draft of the introduction page for non-parametric tests. Let me know what you think about it :)

I got the written content mainly from the canvas page of a course I had last semester and the image in the file is from google images. Should I mention these sources anywhere?

### CODE REVIEW

**Comment by shrabasteebanerjee** [comment]
Hi @Aakriti-G , generally looks good to me - could you please add an intro and conclusion/summary similar to e.g https://tilburgsciencehub.com/building-blocks/automate-and-execute-your-work/reproducible-work/config-vm-gcp/ ?

**Comment by Aakriti-G** [comment]
Hi @shrabasteebanerjee,  I was just waiting for a final confirmation on the content before I added the summary/conclusion. So, now I can add that. As for the intro, I am a bit confused because isn't that just the overview? Should I add anything else as well?

**Comment by shrabasteebanerjee** [comment]
Yes it's basically the overview, but writing it in the form of learning goals/bullets ("after you read this you will be able to:...") may be helpful to follow along...

**Comment by Aakriti-G** [comment]
Hi, I worked over the comments made by @shrabasteebanerjee and I have a second draft for the intro to non-parametric test. Could you please review it and let me know what you think?😄
Also, I am planning on adding here, links to other building blocks which I have not worked on yet. So should we postpone merging this file with the master?

**Comment by shrabasteebanerjee** [comment]
Hi @Aakriti-G , I suggest finishing the binomial BB and then merging. You can continue to work on the others and we'll see how things go -- we can update this BB with links as and when others get done :)

**Comment by shrabasteebanerjee** [comment]
I am merging this for now - when you have content on chi sq and binomial, please update this with the links to those BBs

**Pull request merged**
