### PR TITLE
fix linkedin link for akriti

### PR DESCRIPTION
**Pull request by hannesdatta**
Implemented proper intends in the `.md` file. @Aakriti-G check to see how this was done in the `.md` file.

### CODE REVIEW

**Comment by hannesdatta** [comment]
@thierrylahaije - can you take a look at it? still doesn't work...

**Comment by thierrylahaije** [comment]
@hannesdatta this is very weird. When I run it locally with hugo server, there is no issue, the link is shown correctly. Only the deploy preview shows the wrong link still. Can this be something with the cookies of the preview? Since the .md structure in your branch hannesdatta-patch-2 for aakriti's page is correct and working.

**Comment by hannesdatta** [comment]
Thanks. This was indeed a caching error. @Aakriti-G, your page is up and running.

**Comment by Aakriti-G** [comment]
That's great! Thanks for your help @hannesdatta @thierrylahaije 😄
Was there any issue from my side that I could look out for in the future?

**Comment by hannesdatta** [comment]
Yes. Your markdown wasn't indented properly. You can check other .md files with similar content to learn how to best format these files. Glad it's available now!

**Pull request merged**
