### PR TITLE
Revise multiple building blocks on regression discontinuity design

### PR DESCRIPTION
**Pull request by hannesdatta**
I'm bundling all of @ana-bianca-luca's PRs here to ensure we (a) can review them in their entirety, and (b) they're not blocking the acceptance of other PRs (that are quicker to review).

- [x] #695
- [x] #703
- [x] #711
- [x] #720
- [x] #727
- [x] #732
- [x] #734

I'd say someone needs to take time properly going through them before we merge, just to make sure.

Important points to still address are where to put them on the site, plus a proper content review.

### CODE REVIEW

**Comment by shrabasteebanerjee** [comment]
@kleintob if you have some time in the coming weeks, would you like to have a high level look at the RDD building blocks that Ana wrote? I think they should mostly be correct (since she got input from Lachlan when writing them), but just to make sure. Thanks so much!

**Comment by kleintob** [comment]
@shrabasteebanerjee 
I had a high-level view. Might have missed some things but generally I think this is very good work.
specifics:

- rd-plots seems good
- continuity-rd: two comments:
-- it would be good to incorporate this here http://www.stat.columbia.edu/~gelman/research/published/2018_gelman_jbes.pdf and 
-- to maybe change the name, it's really about flexible estimation; continuity is the backbone of the whole RDD literature
- fuzzy RDD: I'd remove the reference to the fundamental problem of causal inference and I'd restructure this a bit: first say what the sharp RDD is, then say what the fuzzy RDD is; I think in the end of the day it would be good to also state the continuity assumption that we always need, namely that the expectation of the two potential outcomes are continuous at the threshold; this should link to another building block on the potential outcome framework that I'd suggest we add as well (we could also refer to it from other places such as here https://tilburgsciencehub.com/building-blocks/analyze-data/regressions-paneldata/staggered-did/); see Angrist/Pischke book or any other textbook. I like the plots here: https://www.sciencedirect.com/science/article/pii/S0304407607001091, for instance Figure 2 for the sharp RDD, but there is also one for the fuzzy one; this is already there to some extent in the local-randomization building block, and I think it should stay there, but it may be good to talk about it here
- fuzzy-rdd extended needs more work I think, it seems incomplete; maybe explain along the lines of Angrist/Pischke or causal mixtape or the Imbens paper cited in the previous point; structure of argument: we have a discontinuity in the treatment probability and in the expected outcome and we have continuity; if we have a sharp RDD we can estimate the average treatment effect for a subpopulation with the forcing variable in a small neighborhood around the cutoff (formally equal to the cutoff), for a fuzzy RDD we need in addition montonicity and can show that we estimate a local average treatment effect for subpopulation with forcing variable equal to the cutoff; this is due to this paper here https://www.jstor.org/stable/2692190; I think it would be good to add a separate building block on local average treatment effects, as originally discussed in Imbens/Angrist 94--this is the paper that earned them the Nobel prize; this is nicely discusse d in Angrist/Pischke
- fuzzy-rd-in-practice seems good for now
- local-randomization: I'd think of this as a slightly different setup that one can discuss afterwards: the methods have been initially developed for continuously disctributed running variables; I think it's good to write this building block referring to how for that standard case, which should be discussed elsewhere; and where the standard case is discussed one could refer to the local randomization as an extension/alternative setup with some similarities
- validation-falsification: I think the start is a bit ad hoc when one looks at the building block in isolation; also I think it would add real value to provide code and further explanation for all these tests and to maybe do this in the form of a standard list for robstness checks with code; that could be a popular place for empirical researcher: just do the TSH list :)
All in all good effort, but I think some more work would be good before everything can go up. As you can see, I'm missing a bit of structure and guidance, and cross-references. Maybe also good to go back to the basics and watch my video or look at my RDD slides before working on all this: https://www.tobiasklein.ws/open-education

**Comment by shrabasteebanerjee** [comment]
@valerievossen , if you haven't yet started on your instrumental variables BB, would you like to work on this first, since we want to prioritise closing open pull requests over the next 2 weeks? It would be great if you and @MatthijstenTije can divide up the 5 BBs and incorporate Tobi's comments above (Matthijs -- might be better to start on the shiny BBs after this one, in order of priority).  Perhaps Matthijs can do the two on fuzzy RDD, and Valerie can do local randomization and falsification? But you can divide it in any other way too. Thanks!

**Comment by valerievossen** [comment]
@shrabasteebanerjee Yes, can do that first thing this week and will be in touch with Matthijs about dividing them!

**Comment by MatthijstenTije** [comment]
@shrabasteebanerjee Yes, Valerie and I divided them, and I will first start on the RDD building blocks, before starting up R shiny.

**Comment by valerievossen** [comment]
The review is done of the building blocks local-randomization and validation-falsification. I tried to implement Tobias his feedback as good as possible and made other changes to improve the building blocks overall (details are in the descriptions of the commits). Also, I quickly went over the other building blocks in the series to check the consistency and add something like a summary in the end etc. Also I made more references to other building blocks in this series to make visitor click through more. Let me know if anything needs further updates!

**Pull request merged**
