### PR TITLE
Add BB on regression in machine learning

### PR DESCRIPTION
**Pull request by NielsRahder**
Create BB on regression in ML 

@lachlandeer @shrabasteebanerjee let me know what you think!

### CODE REVIEW

**Comment by shrabasteebanerjee** [comment]
Hi @K-sohooli , would you like to start by having a look at Niels' building block on regression/ML, and seeing if anything else can be added? I am also assigning him as your "buddy" to help you with logistical issues. Good luck and keep me posted if there are any questions!

**Comment by K-sohooli** [comment]
Hello,
Thanks for your email.
Yes, sure I will do that.

Best regards,
Kheiry

**Comment by K-sohooli** [comment]
Hi @NielsRahder, do you have time on Monday for a meeting on the Tilburg campus? I want to get involved quickly but first I need some help to get on board.

**Comment by NielsRahder** [comment]
@K-sohooli I've sent you a message on Teams!

**Comment by hannesdatta** [comment]
> Hi @K-sohooli - you and @NielsRahder can work on this one together, after you have reviewed XGboost. Then, send me an updated pull request and I can have a look.

@NielsRahder and @K-sohooli - what's the update on this PR? I think now that I merged #939, you can work on this. Let us know please.

**Comment by lachlandeer** [comment]
superseeded by @K-sohooli's regression ML  building block

**Pull request closed without merging**
