### PR TITLE
Create dask-in-action.md

### PR DESCRIPTION
**Pull request by ana-bianca-luca**
#549 draft of dask-in-action bb

### CODE REVIEW

**Comment by lachlandeer** [comment]
Please make the following changes in an update of the draft: 

* [ ] Title -- Needs an update -- something like  "Using Dask to Describe Data" rather than "How to .."
* [ ] There's no (obvious) link back to the first dask building block -- the motivation seems to need that to help it
* [ ] "Let's see how to load it" -> load the data
* [ ] Suggest that the data has been downloaded and put in the same working directory as a python file that has this code? Makes the lack of directories clearer (actually you use `../` which suggests we go one directory up ... why?)
* [ ] Typo: should be import the `pandas` module

```
# import the Dask DataFrame module
import pandas as pd
```

* [ ] Discussion around the args passed to dask's read_csv is too long and distracts from the point we want to make. Can you shorten that?
* [ ] In "Inspecting the data" can you put a narrative through this rather than dumpinjg code. For example: "One can print the column names to screen using: <Insert code>" Makes it an easier read
* [ ] The point above needs to hold across all code chunks... tell a story rather than dumping chunks of code. 
     - Even better, think of a question you can ask using all the code you've got here and spin that into the text ... something like "I want to find the max and average delay" by airline(?)/airport(?) in the winter months and compare that to the summer months... Now walk me through how to get there using these commands
* [ ] This will make the plotting part more interesting to... compute the average per delay per month,
* [ ] Can you add the output of the code and plotting? So when I read this I can see text, code and output?   
* [ ] Don't add links to all different plotting libraries -- not really the focus here
* [ ] In the conclusion you mention lazy evaluation but don't really talk about it clearly anywhere else... Can you bring that in somwhere?

**Comment by ana-bianca-luca** [comment]
@lachlandeer I incorporated the required changes, but I'm having trouble with aligning the three output images on the same height; not sure if it's a problem with how it looks now.

Note: the problem with the site not displaying codeblocks persists.

**Comment by lachlandeer** [comment]
OK -- looking good. Two final changes:

* [ ] Less of a fan of the images inserted now I see it in action. Let's go without for now.
* [ ] Instead of airline counts per month, can we do average delay? Feels more intuitive in terms of something one might do

Thanks

L

PS. the reason the code blocks don't display is because hugo doesn't understand ```dask or ```pandas but only ```python and ```R

**Comment by ana-bianca-luca** [comment]
> OK -- looking good. Two final changes:
> 
> * [x]  Less of a fan of the images inserted now I see it in action. Let's go without for now.
> * [x]  Instead of airline counts per month, can we do average delay? Feels more intuitive in terms of something one might do
> 
> Thanks
> 
> L
> 
> PS. the reason the code blocks don't display is because hugo doesn't understand ` dask` or ` pandas` but only ` python` and ` R`

@lachlandeer  Is then any way in which I could create two parallel codeblocks named dask and pandas? But putting 'python' also doesn't display them; whatever I do they don't display so I don't know what to do

**Pull request merged**
