### PR TITLE
Non para full

### PR DESCRIPTION
**Pull request by Aakriti-G**
Dear @lachlandeer and @shrabasteebanerjee, I am sharing the latest draft of the 'Introduction to non parametric tests'. This BB contains links to chi-squared test (which has already been merged) but also to unmerged PRs: Binomial test and Wilcoxon test. There are still other tests that are mentioned but do not have the BBs or PRs yet. For those tests I will add the links later. Also, I have inserted an image that I can't see on the website. Is it visible to you?

Please check this out and let me know what you think. Thanks and Happy Carnaval!! 😄

### CODE REVIEW

**Comment by shrabasteebanerjee** [comment]
the summary looks good to me, but I think we should decide whether we want to mention the ones for which we don't yet have content, or do we only keep chi sq binomial and wilcoxon and create a new issue with the remaining ones (eventually updating this BB once we have the other material)? maybe @lachlandeer has ideas

**Comment by Aakriti-G** [comment]
Hi @shrabasteebanerjee thanks for the review. I think it's better if we keep the other tests as it will make this BB more complete and structured. I will try to create the drafts for the remaining tests within the next month (or two at the latest) so we can add the links as soon as possible. But of course it would be nice to hear @lachlandeer views on this. 

Apart from that, this branch has the indexes for the non parametric section which has not been pushed yet and that's why the non parametric section is not visible live on the website. So I have created a new branch in #1077 solely for the two indexes. Can you please have a look there? Thanks! 😄

**Comment by lachlandeer** [comment]
Please only keep links to existing content. 

Perhaps "comment out" the other text, and then once everything is finally published we can simply uncomment the text thats there and have it appear online,

**Comment by Aakriti-G** [comment]
Hi @lachlandeer I already removed the links to the non existing content. Should I put them in as comments and push the file again?

**Pull request merged**
