### PR TITLE
Binomial test new

### PR DESCRIPTION
**Pull request by Aakriti-G**
Dear @lachlandeer @shrabasteebanerjee, I am sharing a new edited draft for the binomial test under the non-parametric test section. Please let me know what you think. Thanks!😃

### CODE REVIEW

**Comment by shrabasteebanerjee** [comment]
hi @Aakriti-G , generally looks good but similar to the earlier draft of chi sq, there is some room to add a more elaborate data example. That way readers can get a better understanding of the use case. Maybe start with some dataset with a few hundred rows of 0's and 1's against a categorical variable, assume some p, and then show how you can aggregate to get numbers of successes and failures which you eventually put into binom.test.  You can also mention the confint function that gives confidence intervals of the proportion: https://whitlockschluter3e.zoology.ubc.ca/RLabs/R_tutorial_Frequency_data.html. It may also be worth mentioning multinomial tests in the end as an extension to binomial: https://rpkgs.datanovia.com/rstatix/reference/binom_test.html

**Comment by Aakriti-G** [comment]
@shrabasteebanerjee thanks for the review. So just to bounce off some ideas about the general layout of the BB, maybe for the "elaborate data" I can analyse a data set with dummy variables, for example, to assess the successes/failures of an event happening. Then I can keep the content already in the draft to fully cover `binom.test()`. After this I introduce `binom.confint()`  using the simple data I already have. Finally, in the end I can mention the multinomial case. I feel like explaining this case might require a new BB so I can work on that additionally. 
What do you think?

**Comment by shrabasteebanerjee** [comment]
you don't need to keep both the die and the coin example, start with 1 of those, then do the elaborate data example, and then the others. for multinomial just add a link to some other blog or resource, basically mentioning that multinomial is a generalization of binomial..

**Comment by shrabasteebanerjee** [comment]
> you don't need to keep both the die and the coin example, start with 1 of those, then do the elaborate data example, and then the others. for multinomial just add a link to some other blog or resource, basically mentioning that multinomial is a generalization of binomial..

or even if you keep both examples to demonstrate one vs two tailed as you currently do, the data example can come after that..

**Comment by Aakriti-G** [comment]
@shrabasteebanerjee Alright, I'll make these changes and send a new draft ASAP. Should I send a PR with a new branch?

**Comment by lachlandeer** [comment]
@Aakriti-G you can add further commits to this branch. They will continue to appear in this PR

**Comment by Aakriti-G** [comment]
Hi @shrabasteebanerjee and @lachlandeer I have pushed the new changes to the file. Please check it out. Thanks!

**Comment by shrabasteebanerjee** [comment]
looks good to go @Aakriti-G !!

**Pull request merged**
