### PR TITLE
913 development call interpreting interactions in r

### PR DESCRIPTION
**Pull request by MatthijstenTije**

### CODE REVIEW

**Comment by MatthijstenTije** [comment]
@shrabasteebanerjee 
The other Building block I have been working on. I added here the model summary tables as well.

**Comment by shrabasteebanerjee** [comment]
Hi @alexandervossen could you have a look at Mathhijs' BB and suggest any improvements? Thanks a lot!

**Review by alexandervossen — CHANGES_REQUESTED** [review]
Thanks @MatthijstenTije ! Looks like a great draft. A couple suggestions: 

- I would start with an example before going into the calculus part. I think it is good practice to always showcase to ask: What kind of questions do interaction effects allow you to answer?  Personally, I feel like dummies as interaction effects are easiest for such examples (such as the ethnicity example you provide below). 
- I am usually not a big fan of using devtools packages for building blocks. It could be suspicious for new users to install packages outside CRAN. I generally use https://strengejacke.github.io/ggeffects/reference/ggpredict.html for this, but I understand if you do not want to redo that part. But maybe then add the possibility of using ggpredict for ploting marginal effects and interactions.
- Speaking of which: I would also add that it is almost always worthwhile to plot interactions to get a better understanding of what is going on. I would include such an advice. 
- I would not necessarily agree that the delta in R2 determines the importance (or negligibility) of an effect.  I would word that a little less sharp.
Hope that helps!
A

**Comment by MatthijstenTije** [comment]
Thanks @alexandervossen for the feedback. I will start working on it shortly!

**Pull request merged**
