### PR TITLE
Create spss-files-in-r.md

### PR DESCRIPTION
**Pull request by StefKirsch**
Added a building block for working with SPSS files in R. For details see #722.

### CODE REVIEW

**Comment by lachlandeer** [comment]
Hey stefan

Thanks for this. 

Some comments to improve before publishing 

- [X] Reduce intro around FAIR (too hard to access essentials easily) ... OK I did this
- [ ] Don't "attach" a data set as it's not how people "should" work. Perhaps assign it to an object `df <- some_assignment()` and go from there
- [ ] The section "Quantitative statistics on ordinal data" seems like content for a new/different building block. as it could be applied to any data not only SPSS data. Remove that for now
- [ ] Add a summary with the 3-5 key takeaways as bullets (see what others have done)
- [ ] We've also started to add learning goals at the top of each building block, can you add 2-3 of those, again look at what others have done.

The stuff on FAIR data principles is itself interesting, and could be a building block on its own if fleshed out more. Let me know if you're interested in this, perhaps by creating an issue and sketching out the headers for each section before proceeding. 

Cheers
L

**Comment by StefKirsch** [comment]
Hi @lachlandeer,
Sorry, I must have missed the email that told me you had posted on this! Thnaks for the feedback! I'll look into it today! 😊

**Comment by StefKirsch** [comment]
Hi @lachlandeer,

I just made a [commit](https://github.com/tilburgsciencehub/website/commit/e8d45877534e7c98c7e155cdc3e938794b37c21b) that addresses your feedback 😊

Regarding this one:
> * [ ]  The section "Quantitative statistics on ordinal data" seems like content for a new/different building block. as it could be applied to any data not only SPSS data. Remove that for now

I think it is important to explain *how* to treat ordinal data as numeric, because it is a very common operation. I tried leaving out the example of questionnaire data, but I felt it made the section a bit confusing. I added a sentences and reworked it slightly so that it's more general and clearer that questionnaire data is just to be seen as an example. Can you live with that?

**Comment by lachlandeer** [comment]
I'll live :)

**Pull request merged**
