### PR TITLE
buildingblock/deltaMethod

### PR DESCRIPTION
**Pull request by ana-bianca-luca**
draft of deltaMethod bb #706

### CODE REVIEW

**Comment by lachlandeer** [comment]
This needs a little more. Here's what I'd add:

- [ ] Some info on what the delta method is, so the reader can grasp what's really going on 
- [ ] The delta method is *really cool* when we want to work with non-linear functions of regression coefficients rather than linear combinations (in fact, I'm pretty sure one doesn't it for linear combinations of coefficients). 
    - [ ] If we want something on linear combinations of coefficients, feels like a different building block (that we should also have!) 
- [ ] Can we find an example where what we're computing with the delta method is something meaningful? as is, it doesn;t feel like one is highlighting the value

If anything's unclear, feel free to reach out to chat

Cheers
L

**Comment by lachlandeer** [comment]
Here's my thoughts on in terms of code

```{r}
# First bit is similar to what you did
library(car)

df <- MASS::Boston

mod <- lm(log(medv) ~ as.factor(rad) + dis + nox + chas + crim + I(crim^2), data = df)

summary(mod)

# Linear
deltaMethod(mod, "crim + `I(crim^2)`", rhs=1) # use names of preds. rather than coefs.

deltaMethod(mod, "chas*(crim + `I(crim^2)`)", vcov = hccm) # adjust for heterosced

# okkk all of the above works, but doesn't deliver any useful quantity
# lets borrow an example of a simple profit max problem for a agricultural producer

library(agridat)
library(dplyr)

df <- hernandez.nitrogen

# lets create an income variable
sale_price <- 118.1
input_price <- 0.665

df <- df %>%
    mutate(income = yield*sale_price - nitro*input_price)

# income is a quadratic in nitrogen use
mod1 <- lm(income ~ nitro + I(nitro^2), data = df)

summary(mod1)

# optimal nitro given prices and coeff (solves a FONC)

optim <- deltaMethod(mod1, "-nitro /(2*`I(nitro^2)`)", rhs=1)
optim

# equiv to
optim2 <- deltaMethod(mod1, "-b1/(2*b2)", parameterNames = paste("b", 0:2, sep = ""))
optim2

# do heterosk:
# equiv to
optim3 <- deltaMethod(mod1, "-b1/(2*b2)", parameterNames = paste("b", 0:2, sep = ""),
                      vcov = hccm)

optim3


# we can actually do the same thing with fixest models
library(fixest)

# add a fixed effect for "site"
mod2 <- feols(income ~ nitro + I(nitro^2) | site, data = df)
summary(mod2)

optim4 <- deltaMethod(mod2, "-nitro /(2*`I(nitro^2)`)", rhs=1)
optim4

# OR
mod_coeff <- setNames(coef(mod2), c("b1", "b2"))
optim5 <- deltaMethod(mod_coeff, "-b1/(2*b2)", parameterNames = paste("b", 0:2, sep = ""),
                      vcov = vcov(mod2))
optim5
```

what would your thoughts be on this? We can also add a linear part for the production example to highlight one could do linear things:

```{r}
optim <- deltaMethod(mod2, "-nitro  + `I(nitro^2)`)", rhs=1)

```

**Comment by ana-bianca-luca** [comment]
@lachlandeer I incorporated parts of your suggested code. What do you think of the new draft?

**Comment by lachlandeer** [comment]
hi! looking good... 

Can you:

-[ ] Remove the "git junk" -- there's a bunch of >>>>> and ==== floating in the file
-[ ] In the overview give the reader a roadmap of what is going to happen in this building block with links to jump between sections
-[ ] You write "approximates the standard error of a ..." in the Implementation section. Could you perhaps elaborate with a formula?
-[ ] In example 2, can you write the equation for the profit function and also the optimal solution so the reader can see that your code is implementing this

Thanks for the good work!

Cheers
L

**Comment by ana-bianca-luca** [comment]
@lachlandeer I made the changes

**Pull request merged**
