### PR TITLE
[content update] Handle-memory-storage-in-GCP

### PR DESCRIPTION
**Pull request by Fernando-Iscar**
Hi Lachlan,

Continuing with what I stated in PR #886, this one would correspond to the second part of the BB [Configure a VM with GPUs in Google Cloud](https://tilburgsciencehub.com/building-blocks/automate-and-execute-your-work/reproducible-work/config-vm-gcp/). In where post VM creation, we'll guide users on accessing storage buckets and managing memory constraints.

Please, also proceed with merging the Docker and Google Cloud-associated PRs (#854, #856, #886) when you find it suitable.

Thanks!

@DiSanchz

### CODE REVIEW

**Review by hannesdatta — CHANGES_REQUESTED** [review]
Hey both,
I've reviewed your work! It looks good, BUT... it's too unrelated for combining it.

Is it possible to split the resource monitoring part from it and have a separate building block? I need to monitor my resources as well but wouldn't have thought this was part of the google cloud series.

As another point, this bert model came as a huge surprise and I was wondering... WHY?

So, either preempt (say upfront this is what you're gonna use to fill up the memory), or replace. Probably preempting is easiest.

Looking forward to your changes!

**Comment by Fernando-Iscar** [comment]
> Hey both, I've reviewed your work! It looks good, BUT... it's too unrelated for combining it.
> 
> Is it possible to split the resource monitoring part from it and have a separate building block? I need to monitor my resources as well but wouldn't have thought this was part of the google cloud series.
> 
> As another point, this bert model came as a huge surprise and I was wondering... WHY?
> 
> So, either preempt (say upfront this is what you're gonna use to fill up the memory), or replace. Probably preempting is easiest.
> 
> Looking forward to your changes!

Thanks for the feedback @hannesdatta !

Indeed makes sense to make two building blocks: one related to storage (this one) and the second about monitoring and handling memory.

In my last commits, I´ve updated this building block so it just discusses about storage management. I will create another PR for the other building block, but this one should be ready now.

Regarding the BERT model, it was meant to be an example of how in some situations you can use batching to handle memory constraints. It was a real-case example since this is how it worked to manage memory issues on one project I worked on with Shrabastee. Nonetheless, I can preempt it in the next building block or I could just think of a simpler example, let us know!

**Comment by Fernando-Iscar** [comment]
The second building block regarding memory allocation is ready to review in #920 

Thanks!

@hannesdatta

**Comment by shrabasteebanerjee** [comment]
Hi @Fernando-Iscar , just double checking the status of this BB -- should I close this pull request and only refer to #920? Thx!

**Comment by Fernando-Iscar** [comment]
> Hi @Fernando-Iscar , just double checking the status of this BB -- should I close this pull request and only refer to #920? Thx!

Hi @shrabasteebanerjee,

No, this PR is for the storage-related building block, while #920 focuses on memory allocation. We split them because they're slightly different topics. Both PRs are ready to merge independently. Thanks!

**Pull request merged**
