### PR TITLE
Topic/interpret summary regression

### PR DESCRIPTION
**Pull request by valerievossen**
Hey @lachlandeer, 

A new topic described in issue #885. 
Let me know if I can make any updates before merging!

### CODE REVIEW

**Comment by krzysztof99xd** [comment]
Nice work @valerievossen !
Very nicely and comprehensively described. 
I have one small comment/suggestion. What do you think about putting results from the confidence interval (`regression_ci.png` picture) into the table instead of having a picture there? I know that for the rest of the article you use pictures but as far as I see, in the rest of the results you highlight certain sections. I believe having a table would look nicer there.

**Comment by valerievossen** [comment]
@krzysztof99xd You're right, thank you for the suggestion! I will update the content :)

**Comment by lachlandeer** [comment]
Hi Valerie

This is **GREAT** -- thanks so much.

Could you perhaps link this post to the modelsummary ones as well? At the end of the article, something like "now if you want to take these estimates/statistics and transform them into a regression table go check these pages out"

Unsure exactly what @krzysztof99xd means exactly by "put in table", so we'll wait for a response there.

Once both of these are integrated, let me know and i can merge it in.

**Comment by valerievossen** [comment]
@lachlandeer Yes good idea. Added a tip box referencing to the modelsummary topic :)

**Comment by valerievossen** [comment]
@lachlandeer Talked to @krzysztof99xd, and made the update suggested in his comment as well now. So, ready to merge!

**Comment by lachlandeer** [comment]
Thanks @valerievossen

**Pull request merged**
