### PR TITLE
First draft of the canonical DiD BB

### PR DESCRIPTION
**Pull request by srosh2000**
Please let me know if you have suggestions to improve this initial draft. Thanks! :)

### CODE REVIEW

**Comment by shrabasteebanerjee** [comment]
looks good to me at a high level! one thing: would be good to include a cleaned up html/latex table for the DID results (using etable, modelsummary or similar -- you can even add a cross reference to the modelsummary building block if you end up using it :) ). otherwise, @lachlandeer can double check for consistency!

**Comment by lachlandeer** [comment]
Some initial thoughts (more might follow):

- [ ] The jump from the ATE section to the illustrative example is pretty big conceptually. 
        - Can we do the "simple" DiD 2 x 2 table with the means, (and compute them + the DiD estimate by hand)
        - Similar to what i do in my SMWA course material that Roshini should have access to
        -  you can relate that back to the nice figure you have
        - (OK on a third read some of it hides in the illustrative example part, suggests we need to make the structure clearer)
- [ ] There's a bit of lack of context around why DiD works and/or why someone might use it.
        - This is OK if we want to assume that the reader already knows what is "going on". But is that the step we want to assume? 
- [ ] The canonical design as the two-way fixed effects model ... can we have an intermediate step as the regression without the TWFE and then discuss why we might want to add them 
        - And any "issues" we might ponder on them causing at the end of the block (eventually linking to future posts?)
- [ ] Do we want to jump straight into a clustered standard error? 
        - Might we want some nuance on why and how and what to cluster on? (unless that's coming in the future, if it is, could we kick clustering down the line to that?)
- [ ] Following on from @shrabasteebanerjee 's comment, a table or coefficient plot might be nice

I don't have a precise idea on how to proceed with this yet. My ideas are in the sub-bullets but need not be exactly what we do... @shrabasteebanerjee -- what do you think?

Integrating all of what I suggest above probably makes this even longer as is (when I read it my first reaction was to split this into 2). What might we think of the following?

- [ ] BB1: The basic DiD setup, 2x2 design table, introduce the example and do the 2x2 table  in R. 
- [ ] BB2: Run the 2x2 table as a regression, add TWFE and explain why one might want to do that
- [ ] BB3 (or integrated into 2): Clustering standard errors in DiD designs

This would be multiple clicks for a reader to go through, but if we think of multiple building blocks being a "tutorial" this might make sense.

**Comment by lachlandeer** [comment]
Great -- do we want to wait and put them all into one PR?

**Comment by srosh2000** [comment]
@lachlandeer Sure thing! Will update this PR with the second BB as well in the coming days.

**Comment by srosh2000** [comment]
@lachlandeer Just finalised the second BB as well! :)

**Comment by shrabasteebanerjee** [comment]
sorry for my delay in responding! i like lachlan's suggestions of splitting the building blocks, and also the other stuff -- looks good to me now except one small cite suggestion :)

**Comment by shrabasteebanerjee** [comment]
Hi @srosh2000 , just checking in about this - I guess you made most of the suggested changes already (other than the small cite comment I had) and this should be ready to merge?

**Comment by shrabasteebanerjee** [comment]
Sounds good, I am merging it since I assume @lachlandeer gave an ok earlier - we can always tweak later if needed!

**Comment by lachlandeer** [comment]
Can we wait until we agree where to put all the casual inference stuff in our meeting on Monday?

I think we might want to decide how to rejig the site to highlight this stuff

**Comment by shrabasteebanerjee** [comment]
ok, let me revert then!

**Pull request merged**
