### PR TITLE
First Draft Article Advanced Markdown Syntax

### PR DESCRIPTION
**Pull request by hannesdatta**
- Created a new subdirectory on the website; inherently it was already there in the title where i set the article

-  Expanded on R Markdown techniques for academic writing, focusing on areas like citation management and dynamic equation generation.

- Linked R Markdown files for hands-on practice.

- Covered topics to complement previous articles, aimed at article writing / the thesis process.

- Structured for stand-alone section use

- Provided practical syntax examples for hands-on application.

- To cover YAML headers I used the  codeblock syntax with plaintext format

### CODE REVIEW

**Comment by hannesdatta** [comment]
Hi @MatthijstenTije,
here is some feedback:

- Can you break up the article in multiple pieces? Will populate our "dynamic document" section + make it easier to find for readers. Suggestion: as per your main headers.

- call it path or directory, not pathway
image

- move an example document for donwload up and create an image so readers know where this gets to
- ensure the sublinks work within an article: did you create relative or absolute links?
- there needs to be one download on top that gets all the code in a zip file so ppl can directly start; copy pasting these maounts of code may be difficult

**Comment by hannesdatta** [comment]
@MatthijstenTije - Please always create pull requests and tag relevant reviewers. Just leaving stuff on a branch and mentioning it in an issue doesn't trigger the regular review cycle. Thanks.

**Comment by lachlandeer** [comment]
@MatthijstenTije is this ready?

**Comment by MatthijstenTije** [comment]
@lachlandeer, everything is ready except for the linkages. It seems to work sometimes, other times not. I find it very confusing, will check soon for a solution.

**Comment by lachlandeer** [comment]
thanks for the update @MatthijstenTije 

Tag me when you're ready for this to be merged

Cheers, L

**Comment by MatthijstenTije** [comment]
@lachlandeer gave it an update! Links are working with hugo server. So if there is no feedback, this can be merged.

**Comment by alexandervossen** [comment]
just skimmed through it - looks good to me - anything else from you @lachlandeer - otherwhise feel free to merge. Thanks @MatthijstenTije !

**Pull request merged**
