### PR TITLE
SEO update 

### PR DESCRIPTION
**Pull request by thierrylahaije**
12/20 files update for SEO.

### CODE REVIEW

**Comment by lachlandeer** [comment]
Hi @thierrylahaije --

Before we integrate this can you write a comment below that at a high level explains the changes that you made? 

Why? So the rest of us can have an idea whats changed etc for a better history (particularly coz your git commits are also not detailed)

Cheers

Lachlan

**Comment by thierrylahaije** [comment]
Hi @lachlandeer,

Sorry for the delay, but of course I can add some information on the updates.
Cas & I have been busy with updating the SEO web structure of certain pages.

The edits that have been made on the pages are as follows:

- I marked some keywords bold / italic. This is important for since Google can only recognize keywords by bold / italic or title tags.
- Some H2 and H1 titles have been adjusted so that Google can understand these H1 and H2 tags and interpret what the specific page is about.

If you want more details about the specific pages and the edits, you can find everything in the following Drive document:

https://docs.google.com/document/d/1xn2WrfSM5kGgGkQ44Uj-3Elt2g4UsYUL/edit?usp=sharing&ouid=109276430175270172396&rtpof=true&sd=true

Cheers,

Thierry

**Comment by lachlandeer** [comment]
@thierrylahaije can you resolve all conflicts?

Let me know if you need further info on how to proceed

**Comment by lachlandeer** [comment]
> Hi @lachlandeer,
> 
> Sorry for the delay, but of course I can add some information on the updates. Cas & I have been busy with updating the SEO web structure of certain pages.
> 
> The edits that have been made on the pages are as follows:
> 
> * I marked some keywords bold / italic. This is important for since Google can only recognize keywords by bold / italic or title tags.
> * Some H2 and H1 titles have been adjusted so that Google can understand these H1 and H2 tags and interpret what the specific page is about.
> 
> If you want more details about the specific pages and the edits, you can find everything in the following Drive document:
> 
> https://docs.google.com/document/d/1xn2WrfSM5kGgGkQ44Uj-3Elt2g4UsYUL/edit?usp=sharing&ouid=109276430175270172396&rtpof=true&sd=true
> 
> Cheers,
> 
> Thierry

I am getting access denied info when I try and access the Google Doc. Find an alternative way to make this available or add my gmail account to be able to view the file (lachlan.deer@gmail.com)

**Comment by lachlandeer** [comment]
Fixed conflicts -- we're in a Building block that got updated. Now merging

**Pull request merged**
