### PR TITLE
937 development call GitHub copilot

### PR DESCRIPTION
**Pull request by VirginiaMirabile**
Hi Alex, 

I have uploaded a draft for the tutorial on Github Copilot. 
Let me know if any modifications are needed and I look forward to discuss it with you. 

Best, 
Virginia

### CODE REVIEW

**Comment by hannesdatta** [comment]
Dear @VirginiaMirabile, I found this PR of insufficient quality to make it to our site. The reason is that it's simply not finished. You have left in placeholders (e.g., "image here"). Please continue your work on this and submit a PR when you are ready. Please also bear in mind the style guide of Tilburg Science Hub, which has a bunch of tips on how to develop your content.

Please also ask another RA to review your content briefly (say, a quick, 10-minute check) before submitting your PR.

**Comment by alexandervossen** [comment]
I also had a look at it after I rendered it locally. I would also say it is worthwhile to expand the text a bit, especially in the intro.  Offer some more use cases and get people curious on how to set it up.  Why not ask copilot to write a tutorial on itself for some inspiration.

**Comment by hannesdatta** [comment]
@VirginiaMirabile - please implement this in two steps.

1) Ensure the building block meets minimum quality criteria, as I outlined above.
2) This needs to be done by tomorrow, as we're preparing for reorganizing content and close PRs for a week.
3) You can make an issue for Alex' request, and - after publication - work on them.

We need something on the site before we close the PRs, and I feel it may take you longer to incorporate Alex' requests.

**Comment by VirginiaMirabile** [comment]
Hi Hannes and Alex, 
Thanks for your suggestions. 
I have already modified the file according to Hannes's previous comments but I have not uploaded it yet as I am having issues with previewing my changes using Hugo, it gives me an error message specifically for this page. 
I didn't want to upload something I was not sure it "looked" good especially with the images. 
I have been looking into resolving the issue with another RA but we haven't figured it out yet. 
Today I will review the file, make the necessary changes, and primarily focus on resolving the preview problem. 

In case, is it okay if I update the file without having previewed it?

**Comment by alexandervossen** [comment]
Can you post the error message? Maybe we can help.

**Comment by VirginiaMirabile** [comment]
This is the message I get: 
Schermata 2023-11-10 alle 17 47 33

I can see the whole website but when I navigate to the tutorial it shows this.

**Comment by alexandervossen** [comment]
That is of course not a very specific error, but I would suggest there is a mistake in the tutorial markdown code that prevents Hugo from rendering that specific site.

**Pull request merged**
