### PR TITLE
Introduction to deep learning

### LINKED ISSUE #1076: Intro to deep Learning
During the onboarding event in the library, me, Lachlan and Matteo were talking about potential articles about Machine Learning.

Since I have started a Deep Learning course at JADS, I said that I could write an article about it and everybody agreed on that. 

Therefore, my initial idea is the following:
- Intro to Deep Learning (would be nice to add basic info what was the inspiration of introducing deep learning in machine learning so neurons in human brain)
- Applications of Deep Learning
- Deep Learning Techniques (I am not gonna go into great detail in order not to make it too complicated but I will introduce basing fundamental techniques such as neural networks, convolutional neural networks ect)
- Code snippets 
- Recent advances (such us transformer models)

### PR DESCRIPTION
**Pull request by krzysztof99xd**
So that is a pull request on my first article on Tilburg Science Hub. We had a conversation with Lachlan and Matteo during the onboarding event that we are gonna develop machine learning section. I decided to introduce our readers to deep learning.
I tried to make an article self-contained, however, basic understanding of programming and math is needed to fully understand the article.

Quick summary of the article:
- intro to deep learning
- components of deep neural networks
- basic math behind deep neural network
- code snippet

@matteozicari  you were also in a machine learning group during onboarding event. Would you like to take a look and maybe provide me with feedback? Thanks in advance!

### CODE REVIEW

**Comment by krzysztof99xd** [comment]
I noticed that images are correctly displayed only in the deployment. When I run the website on my localhost, the pictures are not displayed at all :/

**Comment by lachlandeer** [comment]
Hi @krzysztof99xd 

Since we haven't heard from @matteozicari , let's push this forward... 

Can you:

- [ ] remove the discussion of linking NN to brain activity? I find this to be a bit of a detour that doesn;t help me dive in
- [ ] break up the code in "Coding deep neural network" and discuss it a bit, particularly the layers part. The difficulty curve scales very quickly once someone new gets to this part. (If there's going to be more articles that discuss this in dept, it needn't be super detailed, but as-is its too big a jump)

Thanks!

**Comment by matteozicari** [comment]
Hi @lachlandeer, just sent you a pm!

**Comment by lachlandeer** [comment]
@krzysztof99xd -- any updates on your side? 

It'd be great to get this online soon

**Comment by krzysztof99xd** [comment]
Hey @lachlandeer , thank you for your feedback, and sorry for coming back late. 
I will work on it in the upcoming days and hopefully by the end of the next week the article should be ready. 

I have one remark though. What do you think of shortening (instead of removing) the discussion section linking NN to brain activity?  As this is an introduction to deep learning I find it an important part of this article to know where the models took an inspiration from.

**Comment by krzysztof99xd** [comment]
Hey @lachlandeer , 
I have worked on the article after your comments.  The changes that I made are the following:
- I shortened the Inspiration from the human brain section (I know you wanted to remove it but I believe this is an important part if you want to understand deep learning and neural networks)
- I added a section about optimizer (it is necessary to introduce it because it appears in the code)
- I broke down the code into subsections with an explanation above code snippets

Let me know what you think. 
Thanks!
Krzysztof

**Comment by lachlandeer** [comment]
thanks! this is good!

**Pull request merged**
