### PR TITLE
Machine Learning: Cost and Loss Functions

### PR DESCRIPTION
**Pull request by lachlandeer**
A cleaned up branch of @K-sohooli 's that discusses Loss functions and cost functions in the context of machine learning.

@K-sohooli a to do list:

- [ ] Where did the images come from? Are they public domain? (or have they been taken from elsewhere)
- [ ] can you check that i moved all the images across?

Please make all changes in this branch! `git checkout topic/ml-loss-cost-function-define`

Let me know via tagging me in a comment with answers to the above, and then we can do a next review before integrating, 

Thanks!

### CODE REVIEW

**Comment by lachlandeer** [comment]
@K-sohooli -- 

Can you let me know the answers to the two question above?

Cheers, L

**Comment by K-sohooli** [comment]
Hi @lachlandeer ,
- Regarding the source of images, "costfunctionplot_2" and "2_dim_costfunction" are taken from a course by Andrew NG on the Coursera platform. And I created four other images in Microsoft Word and draw.io .
- regarding the second question, yes all the images relevant to this article are included.

**Comment by K-sohooli** [comment]
Hi @lachlandeer ,
Regarding the source of images, "countourmap_2d" and "2_dim_costfunction" are taken from a course by Andrew NG on the Coursera platform. However, I am not sure if these images are protected by copyright law. If it is needed, I can create these images in Python to avoid any consequences. please let me know if I should create them myself. 
And about the other images, I created them in Microsoft Word and draw.io .
regarding the second question, yes all the images relevant to this article are included.

@lachlandeer , sorry "countourmap_2d" and "2_dim_costfunction" are from the course by Andrew NG. and the others are by

**Comment by lachlandeer** [comment]
Hi @K-sohooli 

What license does Andrew Ng have on his course material? Can you please check whether we can use these images? Else we'll need to create new ones... 

Cheers
Lachlan

**Comment by K-sohooli** [comment]
Hi @lachlandeer , the 2 images are updated. I created them in Python.

**Comment by lachlandeer** [comment]
thanks! merging

**Pull request merged**
