### PR TITLE
Fix-broken-links-correction

### PR DESCRIPTION
**Pull request by jtorralbaflores**
Corrected link errors under topics/visualization/data-visualization and topics/visualization/reporting-tables

### CODE REVIEW

**Comment by jtorralbaflores** [comment]
Corrected links under:

-> content/topics/Analyze/causal-inference/
-> topics/visualization/reporting-tables
-> topics/visualization/data-visualization
-> topics/analyze/regression/linear-regression
-> topics/automation/automation-tools
-> topics/automation/replicability/cloud-computing
-> topics/automation/replicability/docker
-> topics/automation/version-control 
-> topics/automation/workflows
-> topics/collaborate-share/
-> topics/collect-store/data-collection 
-> topics/collect-store/data-storage
-> topics collect-store/computer-setup
-> content/examples
-> content/blog

**Comment by jtorralbaflores** [comment]
You can find the progress on the corrected links in here: https://docs.google.com/spreadsheets/d/12nM-6WTrL0IBsckfcW7jnKRI1IEDGfoM/edit?usp=sharing&ouid=116309553401624618354&rtpof=true&sd=true

Color key:

Grey: corrected
Yellow: either the link was already working or the "broken link" was not found online.

**Comment by jtorralbaflores** [comment]
Note: not all broken links in the report from #1271 were changed. Several of these links were functional and there was no need to change them. For reference, you can look at the Google Sheets file above.

**Review by krzysztof99xd — APPROVED** [review]
It looks fine. Thanks! Thanks for the docs as well. Could you make sure we can access this sheet (google sheet where you documented which links you corrected) also when you stop being a student ?
Thanks!

**Pull request merged**
