### PR TITLE
Correct path for breadcrumps icons

### LINKED ISSUE #1253: #flask: fix icons (e.g., breadcrumbs)
I noticed the breadcrumbs are not working in our new site.

image

Can you please fix?

### PR DESCRIPTION
**Pull request by krzysztof99xd**
Correct path for breadcrumbs. There was a double back slash that made the relative path incorrect.

### CODE REVIEW

**Comment by hannesdatta** [comment]
These icons still remain buggy:

image

Please fix and then change PR draft so I can merge. Thanks!

**Comment by krzysztof99xd** [comment]
I have noticed that this is also not displayed properly on the current version of the website. 
image

I was debugging but the current settings seem to be correct. I can see an error in the console. Can you confirm @thierrylahaije that the kit configurations are correct?

image

Update:
With CDN set up it works. Lets see what is Thierry's opinion on that

**Comment by thierrylahaije** [comment]
@krzysztof99xd @hannesdatta owns the font awesome keys. Could you check whether everything is set correct?

**Comment by hannesdatta** [comment]
any updates?

**Comment by krzysztof99xd** [comment]
According to Thierry, you own the awesome fonts keys @hannesdatta . That where I believe the issue is coming from (please see the screenshot above from the browser console where the number comes from FontAwesome script).

`
	<script src="https://kit.fontawesome.com/4e7776d591.js" crossorigin="anonymous"></script>
`

**Comment by krzysztof99xd** [comment]
During the meeting with Hannes we took the new key from font awesome. I have updated it now in head.html and redirect.html

**Pull request merged**
