### PR TITLE
Intro to chi-squared test - New examples

### PR DESCRIPTION
**Pull request by Aakriti-G**
Dear @shrabasteebanerjee with the help of the links you provided, I have shared the draft for the chi-squared test. Please let me know what you think. Thanks! 😃

### CODE REVIEW

**Comment by shrabasteebanerjee** [comment]
hi @Aakriti-G , the content looks ok to me, but there seem to be some formatting issues when I preview. Make sure that the codeblocks and text are delineated properly and the tables render correctly. Can you check this and let me know?

**Comment by Aakriti-G** [comment]
Hi @shrabasteebanerjee. Thank you for the feedback. I am sorry that that there seems to be some formatting issue. However, everything looks fine to me on the website version. One thing that I can potentially fix is merging the two small codeblocks in the end of the BB into one codeblock. Apart from that, could you please be specific as to where you think the changes are required. Thank you for your patience!

**Comment by shrabasteebanerjee** [comment]
I'm looking at the rich diff version where the codeblocks don't seem to be separated: 
image

perhaps @hannesdatta or @lachlandeer can check the website preview version? I don't have Hugo set up unfortunately.

**Comment by shrabasteebanerjee** [comment]
this table also looks weird in rich diff:

image

**Comment by Aakriti-G** [comment]
Hi @shrabasteebanerjee, this is how I see the table on the website preview version: 

image

But yes, maybe Hannes and Lachlan can confirm if it is fine :)

**Comment by Aakriti-G** [comment]
Hi @shrabasteebanerjee @hannesdatta, nice to see that this PR has finally been merged. However, when I look it up on the website it does not appear very well. Maybe I should change the path on the text editor. Please advise.

image

Apart from this, I have now understood how you want the BBs to be so the other ones should not take so long. 😄

**Comment by lachlandeer** [comment]
it looks fine on the site to me!

**Pull request merged**
