### PR TITLE
Chatgpt article

### PR DESCRIPTION
**Pull request by juliehabets**
I wrote up the draft version of the ChatGPT article. Let me know if it needs tailoring!

### CODE REVIEW

**Comment by lachlandeer** [comment]
I've tried to build this locally and I get a "404 page not found" error when I click on the link from the header 

For now I won't merge it until I can see why this page causes error

**Comment by lachlandeer** [comment]
hey @MKT-Analytics can you try and solve the issue that i raise?

**Comment by MKT-Analytics** [comment]
@lachlandeer The problem was caused by the wrong file name (chat-gpt-**for**-research.md instead of chat-gpt-research.md). I fixed it and updated this branch. It works when I build the site locally, but you can double-check.

**Comment by lachlandeer** [comment]
perfect, merci beaucoup!

**Pull request merged**
