### PR TITLE
Large datasets python

### PR DESCRIPTION
**Pull request by MKT-Analytics**
New Building Block on handling large datasets in Python with Dask

### CODE REVIEW

**Comment by hannesdatta** [comment]
@casruger, could you please review this initially?

**Comment by lachlandeer** [comment]
in general, content looks good ... I'd like to see this with a "real example" though.

I'd propose the following (open to discussion on it)

* Keep this essentially as is (plus or minus some minor edits on grammar / style suggested by others more familar with TSH style)
* A second post that uses Dask in a simple analytics task ... same things that pandas can do, but to highlight differences in implementation / syntax
    * Essentially "Dask in Action" ... perhaps some simple descriptive stats + a group by with descriptives + a variable creation + a filtering step +  a plot ...
    * these are the first set of things I would want to know how to do, and dont wanna have to go elsewhere to learn now you've "got me interested"
    * Do this separately and whenever suits, i.e. don't block a PR for this

The reason I like the second post to be added is that it allows me as a reader to see how to do it in action (and without having to jump to someone else' site to do so)

**Comment by hannesdatta** [comment]
@casruger, can you please review this contribution for style & then make it available?

please also separate out @lachlandeer second suggestion in a separate issue and assign @MKT-Analytics. That way we keep things moving a bit here.

great suggestion, @lachlandeer btw and good work, @MKT-Analytics.

**Comment by casruger** [comment]
@MKT-Analytics  Great tutorial and you made good use of all the markdown features! 

Two (minor) things. Your description is 118 characters. We aim for a description of around 145 characters, so if you could maybe add some more information that would be great. If you can't come up with a better description I will help you. And secondly, I changed the tiles since we usually don't write the titles as 'problem'. If you don't like the new titles let me know.

**Comment by casruger** [comment]
I published the tutorial since the changes are minor and of course can still be done when the tutorial has already been published.

**Pull request merged**
