### PR TITLE
Update versioning-using-git.md

### PR DESCRIPTION
**Pull request by ana-bianca-luca**
#657 add links to Datacamp Github courses

### CODE REVIEW

**Comment by lachlandeer** [comment]
Thanks -- this looks good

Can you also remove/alter the advanced / branching stuff, perhaps by adding a link to the new material we have?

**Comment by ana-bianca-luca** [comment]
> Thanks -- this looks good
> 
> Can you also remove/alter the advanced / branching stuff, perhaps by adding a link to the new material we have?

@lachlandeer I'm not sure what you mean, could you be more specific? Do you mean adding to the 'Advanced use cases - branching' paragraph the links to the branching strategies and naming practices BB's?

**Comment by ana-bianca-luca** [comment]
@lachlandeer I made the changes we talked about, you can review them

**Comment by lachlandeer** [comment]
great -- merging!

**Pull request merged**
