### PR TITLE
First draft Master thesis guide

### PR DESCRIPTION
**Pull request by valerievossen**
Dear @alexandervossen, 

This is the draft Master thesis guide! I put the guide as a series of building blocks with a new header under the "Develop your research skills" section as I felt it fitted there the best. Let me know if it needs to be moved (perhaps as a tutorial structure, but I thought we were moving away from the distinction between tutorials and building blocks).

I am curious to hear your feedback, thank you in advance!

@hannesdatta, I am tagging you as well as it is based on your thesis website. I think it would be good if you have a look at it as well! (Maybe after @alexandervossen gave initial feedback?)

### CODE REVIEW

**Comment by alexandervossen** [comment]
looks great @valerievossen ! Lets have a brief Zoom in the new year to discuss feedback and possible extensions.

**Comment by hannesdatta** [comment]
Hi all,

I have integrated the Master thesis guide into our current structure. However, we can't merge the branch as of now.

@valerievossen, when running this branch locally, you will notice that the master thesis guide is not yet well integrated into our site.

- We need to stop referring to "The Master Thesis Guide" anymore (including "in section 4", etc.) - the material must seamlessly integrate into our site and stand on its own
- I think we need to separate what is GENERAL for any research project and what is specific to theses.
- I also suggest tying in what we already have - e.g., on Overleaf, etc.
- We need to avoid redunandancies (e.g., now we have a "writing guide" for academic papers, and "The Writing of Your Thesis".

When looking at it in our new structure, you probably spot these things as well.

Can you come up with a revision of this branch to integrate it better in what we have, while maintaining the "one-stop-shop" idea for thesis students? (maybe: basics in our article, and specifics linked to other material on our site)? Not sure. 

Looking forward to your input.

**Comment by valerievossen** [comment]
Hi @hannesdatta, thank you for the feedback! Do i understand correctly with your first point to not change the structure that instead of being a sequence, the 4 "sections" of the guide are rather 4 topics on their own? I will work on it and give a heads up in this conversation once the changes are made.

**Comment by valerievossen** [comment]
Hi @hannesdatta, thank you for the feedback! I see what you mean, have some ideas on how to structure it better within the section on the website. I will give a heads-up in this conversation once I am done with restructuring and improving the content.

**Comment by valerievossen** [comment]
An update on what I changed:
- Combine the thesis-outline (chapter structure) with the already existing "writing an academic paper" to avoid all the double information, and make two separate topics: one with general academic writing tips, one about the structure of a thesis or empirical paper 

- Adjust the coding/data topic not just thesis-specific but for any big research project

- Move the content about in the structure of the website: one section is on the writing process and one on the data/coding related content 

- To keep the “one-stop-shop” idea, I added a summary block in the beginning of the Preparation
phase, bundling all the topics that apply. Also I think it's quite clear from the titles which topics apply for students doing their thesis. 
However, we don't completely have the "guide" idea anymore. Therefore, another option would be to have another “topic” called the "Master Thesis Resource Bundle” , and list the content in here. I added this as well for now, but I am not sure whether this will make readers stay because they immediately have to click through for content. What do you think about this? @hannesdatta 

I will still go through the content once more to check for things to tie in.

**Comment by alexandervossen** [comment]
Thanks @valerievossen I checked out your new changes today. I am not sure I 100% agree with @hannesdatta that the thesis guide should not stand for its own. I personally feel the previous version felt much more like the "check list" I had in mind.  Don't get me wrong-I like the cross references and synergies to existing content and we should heavily rely on that-but the guide now feels a bit blurry and deprived of the "click this link and it will guide you step by step through what to do" factor. It is, to my mind, not exactly the same as writing an academic paper and I personally feel there is sufficient reason to have a dedicated "thesis guide" as a topic.  But maybe that is a discussion for me and @hannesdatta to have and of course I may also be wrong :) Lets maybe briefly sync our perspectives in the next WOW and see that this great guide gets live :) A

**Comment by alexandervossen** [comment]
> An update on what I changed:
> 
> * Combine the thesis-outline (chapter structure) and writing part of the thesis guide with the already existing "writing an academic paper" to avoid all the double information, and make two separate topics: one with general academic writing tips, one about the structure of a thesis or empirical paper
> * Adjust the coding/data topic not just thesis-specific but for any big research project
> * Move the content about in the structure of the website: one section is on the writing process and one on the data/coding related content
> * To keep the “one-stop-shop” idea, I added a summary block in the beginning of the Preparation
>   phase, bundling all the topics that apply. Also I think it's quite clear from the titles which topics apply for students doing their thesis.
>   However, we don't completely have the "guide" idea anymore. Therefore, another option would be to have another “topic” called the "Master Thesis Resource Bundle” , and list the content in here. I added this as well for now, but I am not sure whether this will make readers stay because they immediately have to click through for content. What do you think about this? @hannesdatta
> 
> I will still go through the content once more to check for things to tie in and fix any small things (also the images are not rendering yet when I run locally)

Hi @valerievossen  - did you find anything? Othwerwhise I would merge it :)

**Comment by valerievossen** [comment]
@alexandervossen Yes, these commits are done after that comment was placed so should be ready to merge!

**Pull request merged**
