### PR TITLE
995 development call literature research using the scopus api

### PR DESCRIPTION
**Pull request by VirginiaMirabile**
Hi @alexandervossen and @lachlandeer,

I am creating a pull request for the introductory tutorial on how to use Scopus for literature reviews. 
Please have a look at the content and let me know if the images work as they don't preview locally. 

Have a nice weekend!

Best,
Virginia

### CODE REVIEW

**Comment by alexandervossen** [comment]
Thanks @VirginiaMirabile - I will have a look at it! @gbocsardi want to give it a look too?

**Comment by VirginiaMirabile** [comment]
I have just tried to preview it locally from VS Code and it works properly. I will have a look at it and see what might be wrong. 
Schermata 2024-03-05 alle 12 03 10

**Comment by alexandervossen** [comment]
Maybe its me then :) Maybe @gbocsardi can check as well :)

**Comment by VirginiaMirabile** [comment]
Okay, keep me updated!

**Comment by gbocsardi** [comment]
So I checked the problem out. When you click "Topics", then you get to the same situation where @alexandervossen was, where it's weird. But if you hover "Topics" and the dropdown opens (
image
), then it's there, working properly.

Other comments:
- the scopus homepage image looks broken, the other pictures show, but that one doesnt,
- same with "inspect additional data" image.

I really like it, @VirginiaMirabile you did a great job!

**Comment by lachlandeer** [comment]
@VirginiaMirabile 

This is great

Can you make one change for us:

- [ ] Instead of a conclusion paragraph, can we have a summary box at the end. This fits in closer to our common structure across most articles. 

tag me when this is done and will merge it

Thanks!

**Comment by gbocsardi** [comment]
Hi everyone, 

@StefKirsch just told me that Tilburg doesn't officially support Scopus, and they don't recommend using it (there is some politics involved). @VirginiaMirabile  before you push the new version, could we have a short meeting about this?

**Comment by hannesdatta** [comment]
Please loop me in on this on Teams. Do recall we are writing for a broad audience and target also researchers outside of TiU.

**Comment by VirginiaMirabile** [comment]
@gbocsardi yes sure, I am free today from 10:30 to 12:45, otherwise we can talk on Monday after the Wow.

**Comment by alexandervossen** [comment]
> Please loop me in on this on Teams. Do recall we are writing for a broad audience and target also researchers outside of TiU.

I agree!

**Comment by lachlandeer** [comment]
@VirginiaMirabile @alexandervossen 

where are we at with this?

**Comment by VirginiaMirabile** [comment]
Hi @lachlandeer, sorry I have been busy with my thesis proposal. I will submit a pull request latest tomorrow evening!

**Comment by VirginiaMirabile** [comment]
Hi @lachlandeer, I have implemented your feedback. Should be good to merge now!

**Comment by alexandervossen** [comment]
@VirginiaMirabile Thanks! I am only a poor man's  @lachlandeer but I merged it :) Thanks alot!

**Pull request merged**
