### PR TITLE
First draft of remake BB

### PR DESCRIPTION
**Pull request by srosh2000**
@hannesdatta @lachlandeer Here's a first draft of the building block on debugging makefiles using remake. Please let me know if this is fine or if further changes are required. 

Thanks!

### CODE REVIEW

**Comment by lachlandeer** [comment]
Overall I like it, and I learned something new :) . Some changes to make to get this all the way

* The text in the figures is too small to read easily (at least with my old man eyes). Can we make these bigger somehow? Maybe re-doing what you have but with a larger font on your bash terminal (I teach with a font size of 24 or larger and I think this also makes readable images)

Small changes to aid readability:

In Overview:

* First paragraph is great as an essay - but it has a "too long, won't read" vibe when i open the page. Try and compress to one must read sentence

* rework second paragraph to emphasis remake as a debugger. This took me two - three reads to get, Example as a first sentence

"Remake" is a tool that can help us to debug errors that have occured in a makefile / make build. 

In steps to debugging:

* Does this workflow exist somewhere? If i really want to invest in this page I will want to follow along by typing what you do
    - If its only hypothetical, the example directory tree feels too large to make the point we're going for

* Before you go thru each subheader, can we have a bulleted list of here's what we're gonna do and a very short sentence explaining what that means. 

From "In summary" have a section header "Summary"

Extras: 

* Somewhere in the post can we link to the existing make stuff? The Related posts bit does a terrible job right now

* Can you move this post in the header to be with other `make` content? The "Automate your workflow" section is messy as is but having make stuff not in order adds to the messy feeling

Thanks!

**Comment by srosh2000** [comment]
@lachlandeer Thanks a lot for the feedback! I have incorporated the feedback and made the following changes:

- edited the overview paragraph
- increased font of the terminal and uploaded new images with larger font 
- added a quick steps overview
- added summary block in the end 
- added 'see also' section to link existing make posts
- there is indeed an existing directory linked to this building block for people to follow along so I didn't change the directory structure tree stuff

Please let me know if additional changes are required.

**Comment by srosh2000** [comment]
@lachlandeer Thanks for the feedback! Just made changes. 

- I agree that the section is tad bit cluttered. I changed the weight parameter values but I think in general that section needs some restructuring so perhaps creating new sub headers/folders would help. Also, some .md files seem unrelated to automate workflows(e.g. share large temp files). I will create a new issue and restructure this bit.. ?



- Also: Once this BB is finalized I can link it to the bigger tutorial we have on make: https://tilburgsciencehub.com/tutorials/reproducible-research-and-automation/practicing-pipeline-automation-make/pipeline-automation-overview/ 

PS: if the code snippets don't show up immediately when you locally host it, please try clicking the refresh button multiple times ( worked for me then!)

**Comment by lachlandeer** [comment]
awesome job -- merging this

**Pull request merged**
