### PR TITLE
Topic/parallel computing r

### PR DESCRIPTION
**Pull request by valerievossen**
Hi @Fernando-Iscar, 

This is the topic of parallel computing (issue #284). Can you proofread it quickly before I ask Hannes to review it?
Also, I was not sure whether this section (/computer-setup/develop-coding-skills/coding-practices) is a good one to put it? Any other suggestion?

Thanks in advance!

### CODE REVIEW

**Review by Fernando-Iscar — CHANGES_REQUESTED** [review]
Thanks @valerievossen ! 
I really like how you explain it, I just saw few typos while reading it.

Another observation is that with these examples we cannot really see the benefits of parallel computing, as both examples with pararellization have longer executing times than without it. This may likely be due to [Amdahl's Law](https://en.wikipedia.org/wiki/Amdahl%27s_law). 

So what I'd do is : 

- Change/add a coding snippet to have an example showcasing that parallelizing helps reducing execution times for loops and repetitive tasks, also pointing up that it can help avoid memory runtime errors. 

- Add at the end a final section on 'When to parallelize', similar as it's explained in [this site](https://nceas.github.io/oss-lessons/parallel-computing-in-r/parallel-computing-in-r.html), which also contains a good plot of Amdahl's Law plus some coding examples you could get inspiration from.

If you need some help or something let's talk in Teams :)

**Comment by valerievossen** [comment]
Thank you @Fernando-Iscar for the useful feedback, I implemented those and the examples show the benefit of parallelization now! 

@hannesdatta would be great if you can have a review before merging !

**Comment by valerievossen** [comment]
@hannesdatta this was the PR I mentioned during the WOW meeting, in which I didn't tag you yet - i'm sorry :)

**Comment by lachlandeer** [comment]
This looks ok to me as-is

@hannesdatta if you're good with it, feel free to merge, if it's still here in 7 days I wll merge it assuming you're OK as-is

**Review by hannesdatta — APPROVED** [review]
Hi @valerievossen, the content was great, but I found the write up to be improvable. I have done some touch ups and the article is now good to go. It's worthwhile using grammarly and good ChatGPT prompts to do a copy-editiing job before you submit work next time. Experiment a bit with prompts (I always tell it NOT to change any source code and focus on copy-editing the text to ensure flow, make it easy to understand etc.).

**Comment by valerievossen** [comment]
@hannesdatta alright, thank you! I see what you mean, will do next time.

**Pull request merged**
