### PR TITLE
Revert "Update theory-best-practices.md"

### PR DESCRIPTION
**Pull request by shrabasteebanerjee**
Reverts tilburgsciencehub/website#950

### CODE REVIEW

**Comment by shrabasteebanerjee** [comment]
@VirginiaMirabile can you double check this to see whether all plots and code render correctly? I merged it earlier but there were some broken images on the website...

**Comment by VirginiaMirabile** [comment]
I have just updated the code for showing images, let me know if this works.

**Comment by shrabasteebanerjee** [comment]
@hannesdatta something seems to be off with the images in this BB and somehow I can't fix it. If you can have a look that'll be awesome. Thank you!

**Comment by VirginiaMirabile** [comment]
Hi Shrabastee, I have just created a pull request in the branch visualization-theory for what I think is the correct file to be merged. Valerie helped me to fix the images that were not showing and now everything should be okay.

**Pull request closed without merging**
