### PR TITLE
Wilcoxon

### PR DESCRIPTION
**Pull request by Aakriti-G**
Dear @lachlandeer and @shrabasteebanerjee, I am sharing the draft for the Wilcoxon test BB under the 'Non parametric test' section. Please check it out and let me know what you think. 😄  Thanks and Happy Carnaval!

### CODE REVIEW

**Comment by lachlandeer** [comment]
hi @Aakriti-G 

each of your PRs contains changes to multiple pages , i.e. this PR has updates to binomial and wilcoxen. 

Can you update this so a PR contains only one new building block? Otherwise as we request updates on one branch we will start to see conflicts with the others that we'l need to work through

Thanks!
Lachlan

**Comment by shrabasteebanerjee** [comment]
Hi @Aakriti-G , it would be good to show some figures like in this blog, to make the distributions and non normality clearer to readers: https://statsandr.com/blog/wilcoxon-test-in-r-how-to-compare-2-groups-under-the-non-normality-assumption/ . Also, you should emphasize that we would typically use wilcoxon for smaller samples where normality is unlikely to hold. Maybe also adding this as a note/tip (from the blog): "One may wonder why we would not always use a non-parametric test so we do not have to bother about testing for normality. The reason is that non-parametric tests are usually less powerful than corresponding parametric tests when the normality assumption holds."

**Comment by Aakriti-G** [comment]
Dear @shrabasteebanerjee, I have made the changes as you suggested. The only thing is that, for showing the histogram with the no normality, I have used the one sample data because doing so, fit the flow of the BB better. Please let me know what you think. Thanks :)

**Comment by shrabasteebanerjee** [comment]
thanks aakriti - this looks great! we should be ready to merge.

**Pull request merged**
