### PR TITLE
Topic/serial correlation

### PR DESCRIPTION
**Pull request by valerievossen**
Dear @alexandervossen, 

This is the PR for the topic of serial correlation. Thank you for revising it, I am curious to hear your thoughts!
In particular, I have a few points I would like your feedback on: 
- The alternative test I proposed for fixest models; I am wondering about its validity compared to traditional statistical tests. If this approach is somewhat complex or not as robust, an alternative would be to suggest re-estimating the model with plm before conducting a serial correlation test. If you know about any alternative function for serial correlation tests for 'fixest' models, let me know! I couldn't find anything online.
- I made a new section for "Testing for OLS Assumptions". Especially with Matthijs working on Heteroskedasticity tests, I thought it would be a suitable section (name). 
- I think more information comparing the three statistical tests would be beneficial, but I didn't manage to find much on the advantages of one to the other, or when to prefer one over the other. Do you know more about this?

### CODE REVIEW

**Comment by valerievossen** [comment]
@alexandervossen this is ready for review now!

**Comment by alexandervossen** [comment]
> @alexandervossen this is ready for review now!

Looks great! One minor thing on the fixest part: It is my understanding that clustered SE are also always heteroscedaticity robust. So the  vcov = "hetero" should be redundant. Maybe leave it out and the SE should be the same. Maybe change this and the next paragraph as it may confuse.  Otherwhise great!

**Comment by lachlandeer** [comment]
@alexandervossen @valerievossen 

indeed, clustering gets the heteroskedasticity bit "for free"

@valerievossen : can you also fix the merge conflict, then can integrate!

**Comment by valerievossen** [comment]
@lachlandeer there is a conflict with the new version after the PR of heteroskedasticity is merged. Just to clarify; we want a section with "Tests" and within this subsection of "Non-parametric tests" and "Assumption tests" with the latter containing the heteroskedasticity and serial correlation, right? Then something went wrong with the folders in the other PR as now it looks different than this. I will change it in another PR if you confirm!

**Comment by valerievossen** [comment]
Schermopname (722)

**Comment by valerievossen** [comment]
Yes, conflict is solved and this one is ready to merge! Thank you.

**Pull request merged**
