### PR TITLE
update literature search block

### PR DESCRIPTION
**Pull request by hannesdatta**
Hi @Tomeulnv, I have suggested some changes here. When writing articles for TSH, try to use a lot of bullet-point style, headers, etc. And we have these amazing tip/warning/summary boxes. Use them when appropriate (see my changes here).

@andreantonacci, can you integrate but first check w/ it all renders well? did the editing on GitHub itself.

### CODE REVIEW

**Comment by hannesdatta** [comment]
@Tomeulnv, fyi:

```
{{% tip %}}

This is a tip

{{% /tip %}}
```

**Comment by hannesdatta** [comment]
@andreantonacci, please fix the formatting here and then merge.

image

**Comment by Tomeulnv** [comment]
Okay,  thank you for the feedback @hannesdatta . As for the content of it, do you feel it's missing for instance info on Crossref? Tbh I have never used it, but might be interesting to add?

**Comment by hannesdatta** [comment]
Crossref is cool because it's a very reliable source of data. so, it gives you a "clean" record, w/ correct author names, etc. Can you just add it as an alternative to scholar to search for records (including books, I think)?

Just incorporate and then tell @andreantonacci to merge. Thanks!

**Comment by hannesdatta** [comment]
@Tomeulnv, there seems to be some merging issue w/ this PR; can you figure out what's wrong and change the file so I can merge it without editing? Prob both you and me changed some stuff here... thanks!

**Pull request closed without merging**
