### PR TITLE
introd_ghactions

### PR DESCRIPTION
**Pull request by DiSanchz**
This pull request covers the first version of the first building block of the series on GitHub Actions and Unit tests. Is meant to work as a conceptual introduction to GitHub Actions, presenting the platform, some of its fundamental concepts, and how to adapt a project directory structure to use GH actions. This will be followed by a building block where a workflow for code formatting and testing is used as a reference to explain how to build GH Actions workflows and the details of these, which are reviewed in this building block only in a conceptual manner.

Let me know what you think of it and any comments or suggestions you may have to improve it!

@shrabasteebanerjee 
@narendramukherjee

### CODE REVIEW

**Comment by shrabasteebanerjee** [comment]
@DiSanchz added two small amendments, otherwise looks good!

**Comment by lachlandeer** [comment]
hey @shrabasteebanerjee 

are you Ok with the content in this as is? I think it looks good

**Comment by shrabasteebanerjee** [comment]
> hey @shrabasteebanerjee
> 
> are you Ok with the content in this as is? I think it looks good

Yes the overall content looks good, we only need the two small fixes about the second building block. @DiSanchz was traveling the last few days, but I guess he can double check by next week!

**Comment by shrabasteebanerjee** [comment]
Hi @DiSanchz ! Could you make the edits that refer to the second building block? Then we can merge this

**Pull request merged**
