### PR TITLE
buildingblock/matplotlib-seaborn

### PR DESCRIPTION
**Pull request by ana-bianca-luca**
draft of matplotlib vs seaborn bb #737
@lachlandeer I used a dataset (the monthly stocks) that I had locally since a long time but I can't find it online so I tried to upload it and make it a downloadable file, but i'm not sure it works...any suggestions?

### CODE REVIEW

**Comment by lachlandeer** [comment]
Something strange happens when i try to build this locally -- and i can view the content

2023-08-14 - 16-41-57 - Tilburg Science Hub


Can you see whats wrong and perhaps fix that? Then I'll look over the content

**Comment by ana-bianca-luca** [comment]
> Something strange happens when i try to build this locally -- and i can view the content
> 
> 2023-08-14 - 16-41-57 - Tilburg Science Hub
> 
> Can you see whats wrong and perhaps fix that? Then I'll look over the content

@lachlandeer that seems like an error caused from the lack of the _index.md files, but I uploaded them with the theory bb, when I first created the new folders. I uploaded them again in this PR, so this should work now

**Comment by hannesdatta** [comment]
It now builds - the ` ```{stata}` needs to be ```stata.

image

**Comment by hannesdatta** [comment]
I've revised this building block to make an initial version publishable. I will create a new issue for someone w/ a data science background to review the content and enhance it.

**Comment by hannesdatta** [comment]
I've revised this building block to make an initial version publishable. We will wait for merging it until #736 is on the site.

**Pull request merged**
