### PR TITLE
draft bb git-commits

### PR DESCRIPTION
**Pull request by ana-bianca-luca**
create draft of git-commits bb #606

### CODE REVIEW

**Comment by lachlandeer** [comment]
This is great. 

One change to improve readability:

- [ ] Can the intro have the "what we're gonna do" before the questions? Easier to digest. Then can the questions be a bulleted list?

Thanks for your hard work!

**Comment by ana-bianca-luca** [comment]
@lachlandeer i made the changes

**Comment by lachlandeer** [comment]
thx!

**Comment by lachlandeer** [comment]
closes #606

**Pull request merged**
