### PR TITLE
buildingblock/visualization-theory

### PR DESCRIPTION
**Pull request by ana-bianca-luca**
draft of data visualization theory and best practices bb #735

### CODE REVIEW

**Comment by lachlandeer** [comment]
This is interesting -- thanks! 

Some comments: 

- [ ] The jump straight into "Theory" feels a bit rough on the reader. Can we smooth this out, either making it a bit chattier, or with an example plot that you can use to relate back to as the first thing a reader sees (with some description).
- [ ] Where have these figures come from? Do we need to attribute them to someone or have you created them yourself?
- [ ] Doesn't feel like a complete list of chart types. So why these? Is there a motivation? Can you be explicit on this being a subset of the type of plots one might choose
- [ ] Each of these tips at the bottom feel like useful content for future building blocks ... Any thoughts on that? (for someone else to do)

**Comment by ana-bianca-luca** [comment]
> This is interesting -- thanks!
> 
> Some comments:
> 
> * [x]  The jump straight into "Theory" feels a bit rough on the reader. Can we smooth this out, either making it a bit chattier, or with an example plot that you can use to relate back to as the first thing a reader sees (with some description).
> * [ ]  Where have these figures come from? Do we need to attribute them to someone or have you created them yourself?
> * [x]  Doesn't feel like a complete list of chart types. So why these? Is there a motivation? Can you be explicit on this being a subset of the type of plots one might choose
> * [ ]  Each of these tips at the bottom feel like useful content for future building blocks ... Any thoughts on that? (for someone else to do)

@lachlandeer Some of the figures are from a 1st year course from my bachelor, while others are taken from the google images page. So should we reference somehow?
The tips at the end could indeed be expanded in another bb, something like "Best Practices Extended", where each of the 7 points are explained further with example charts of how not to do it, and then the right way.

**Comment by hannesdatta** [comment]
This is ALMOST ready to go. 

However, I need @shrabasteebanerjee to assign a member of our RA pool here to 

- [ ] provide code for each plot that we generate (you can create similar plots with a dataset of your choice - you could also "simulate" a data set; try it out w/ ChatGPT if you don't know how to get started) - use ggplot2 in R
- [ ] replace the plots that we currently show with the plots that we generate
- [ ] add a section to the building block on how to save plots for publication (typically using ggsave in the case of ggplot in R).

I'm not merging this PR for now because some of the images are not ours and first need to be replaced.

**Comment by shrabasteebanerjee** [comment]
Hi @VirginiaMirabile , just to confirm, it seems that you have already addressed Hannes' comments above. If so, can I close this pull request?

**Comment by VirginiaMirabile** [comment]
Hi Shrabastee, yes I have. Thanks!

**Pull request merged**
