### PR TITLE
Fix for issues #1030, #1031 and #1036

### PR DESCRIPTION
**Pull request by thierrylahaije**
Fix for issues #1030, #1031 and #1036

### CODE REVIEW

**Comment by thierrylahaije** [comment]
Added the fix for issue #977 as well.

**Comment by lachlandeer** [comment]
hey @thierrylahaije 

Checks are failing. Please update, then ping me to merge

Cheers
L

**Comment by thierrylahaije** [comment]
Hi @lachlandeer 

I checked the branch locally and there are no problems when running, also no merge conflicts so I do not know what the exact issue is. These checks also fail sometimes when I add or correct new features, so I don't know whether these checks are correct, since I updated features in this branch. The logs from the checks are also unclear. What do you want me to do?

**Comment by hannesdatta** [comment]
I've verified this PR can be merged. Thanks, @thierrylahaije - somehow got stuck in my pile of to do's. Plus thanks @lachlandeer for taking a look at this.

**Comment by hannesdatta** [comment]
Ha, there was an issue, after all. Thierry, I've seen this more often - the code committed by you sometimes has extra line breaks. When this happens in a `{{` bracket, then Netlify doesn't deploy (while hugo does build locally - guess this has to do with version numbers or something like that).

Something to watch out for, ok?

Thanks a bunch!

**Comment by thierrylahaije** [comment]
Hi Hannes,Great that you found the issue! The line breaks have to do with the standard formatting by Visual Studio Code (mine is set for web applications and web development, to keep structures clear). I will keep it in mind for the future pushes so that there will be no issues.Kind regards,Thierry Verstuurd vanaf mijn iPhoneOp 4 feb 2024 om 21:40 heeft Hannes Datta ***@***.***> het volgende geschreven:﻿
Ha, there was an issue, after all. Thierry, I've seen this more often - the code committed by you sometimes has extra line breaks. When this happens in a {{ bracket, then Netlify doesn't deploy (while hugo does build locally - guess this has to do with version numbers or something like that).
@thierrylahaije
Something to watch out for, ok?
Thanks a bunch!

**Pull request merged**
