### PR TITLE
Update of building block 742

### PR DESCRIPTION
**Pull request by MatthijstenTije**

### CODE REVIEW

**Review by hannesdatta — CHANGES_REQUESTED** [review]
Hi @MatthijstenTije, good work so far. Please implement the following things (ensure that you pull a recent copy of my changes before making any changes).

- The figures/images you are referring aren't loading - I don't think you have committed them with this pull request. Can you check?
- I have made some changes to the formatting of your arguments - can you please apply them consistently in this building block (e.g., I did it for #### 1. and ####2.)
- I don't get point 3. `readr` is part of `dplyr`, I believe. I know it was true in the past `data.table` didn't create copies and `dplyr` did, but is that still the case? Please check.
- You are showing code in your building block that users do not have access too. Maybe refer to a dataset users can download so they can implement your snippets/try them out? 
- You have always present `data.table` first in your initial write-up, and then you switch to first talking about readr, then data.table. Please try to be consistent.

Finally, it is always a good idea to preview your changes with Hugo. See:

Host our site local to see your changes

If you want to make changes to, for example, our templates, or you want to see how your changes will look on the site you have to run our site locally using Hugo.

    Have Hugo installed. If you do not yet have Brew and Hugo installed follow [the tutorial Get Hugo](https://tilburgsciencehub.com/tutorials/open-education/hugo-website/get-hugo/)

    Fork the originating repository to your GitHub profile (press the “fork” button on GitHub, which creates a copy of this project in your own GitHub account).

    Within your version of the forked repository, move to the tilburg-update branch and create a new branch for each significant change being made.

    Navigate to the file(s) on your computer. This most easily done via GitHub desktop.

    Once you are in the folder type cmd in the address bar and press enter

    In the Command Prompt type hugo server to make the website run local. A local host link will be given (http://localhost:xxxx).

**Comment by shrabasteebanerjee** [comment]
@MatthijstenTije just checking if you made some of the changes hannes suggested above?

**Comment by shrabasteebanerjee** [comment]
(I don't know if I merged the wrong pull request about large datasets in r...)

**Comment by MatthijstenTije** [comment]
@shrabasteebanerjee Yes I made the changes Hannes suggested and yes I am sorry, but this is the latest one.

**Comment by MatthijstenTije** [comment]
Can I do something, to make correct it/  make it work @shrabasteebanerjee?

**Comment by shrabasteebanerjee** [comment]
Thanks Matthijs -- @hannesdatta could you have a quick look to resolve the merge conflict?

**Comment by hannesdatta** [comment]
It also took me a while to figure out what is the correct version but now I'm there! MATTHIJS, this looks great! A recommendation to all of my students. Good work.

**Pull request merged**
