### PR TITLE
first draft of fixest BB

### PR DESCRIPTION
**Pull request by srosh2000**
@lachlandeer Here's a first draft of the BB on fixest. I have narrowed down the content based on what I know best of the package from personal use but please let me know if further elaboration is needed or if I'm missing out on something content wise. Or general structure stuff...

@alexandervossen I remember you mentioned having worked with fixest a lot in the past so please pitch in if you have any feedback! 

Appreciate it, 
Roshini

### CODE REVIEW

**Comment by alexandervossen** [comment]
Hi Roshini

Looks good! One of the strong suits of fixest is that it allows a quick estimation of high dimensional fixed effects (such as I have them in one paper with 7000 dimension product fixed effect). They do this via alternate projecting (some stats voodoo if you ask me:)). I will update it once it is live and also write something about the table function it provides for reporting and the clustering of the standard errors. That is just super convenient as compared to PLM or any other package.

I just have a more general question (Maybe also partly for Lachlan): Would it not make sense to to make such posts as a .rmd file? This would also allow to use the R code directly without any png screenshots. I also use Hugo and that is how I do it on my personal website. For example:
Published post: https://alexandervossen.github.io/post/plotting-u-shapes/
The .rmd file is attached. I just drop this into the folder and Hugo does the rest :) But I compile my website with R studio and not netlify - I do not know wether there is a differrence.


Anyways cool start!

Cheers
A

————————————————————————
Alexander Vossen
Tilburg University
Jheronimus Academy of Data Science (JADS)
Data Entrepreneurship Group
https://www.tilburguniversity.edu/staff/a-vossen
https://alexandervossen.github.io<https://alexandervossen.github.io/>

Am 05.04.2023 um 17:26 schrieb netlify[bot] ***@***.***>:

﻿

👷 Deploy Preview for unique-scone-f4eb67 processing.
Name    Link
🔨 Latest commit        cd3fb9e<https://github.com/tilburgsciencehub/website/commit/cd3fb9ef11eb77223a2b74baf44fe0a17717f409>
🔍 Latest deploy log    https://app.netlify.com/sites/unique-scone-f4eb67/deploys/642d930b4c80320008a6122d

**Comment by lachlandeer** [comment]
I'll get back to you re: the fixest content soon.

On the integration of Rmds etc, @shrabasteebanerjee @kleintob and I were discussing this in a meeting today. We weren't sure if our existing hugo template would support this but will likely reach out to our developer soon with this as part of a to do list

**Comment by lachlandeer** [comment]
@alexandervossen when you want to work on the table function (`etable()` ?) Let's chat about how we can do this in a way that provides a nice comparison to `modelsummary()`

We're working on a simple modelsummary building block here #613 so once we have this and that, I can see a nice post mixing together and comparing to etable when one has a bunch of fixest models they need to put into a table

**Comment by srosh2000** [comment]
@lachlandeer I managed to incorporate most feedback except the point about the csw() function. For some reason it seems like it is not part of the fixest package( at least the version I am on : 0.9.0). When I looked up the help function it looks like this function is used for stepwise estimation. Wanted to check with you if this is what you mean? If you have link to a documentation or something I'm happy to check again. 

Otherwise, please let me know if the modifications are okay. Thanks!

**Comment by lachlandeer** [comment]
This is great -- merging it in

Thanks @srosh2000 for integrating all suggested changes

**Pull request merged**
